// Generated by scripts/export_frontend_emails.py - do not edit by hand.
// Source of truth: fixtures/emails/*.json

export type SampleEmail = {
  id: string;
  scenario: string;
  docTypeExpected: string;
  plantedFlaw: string | null;
  from: string;
  subject: string;
  text: string;
};

export const SAMPLE_EMAILS: SampleEmail[] = [
  {
    "id": "001_shipping_normal",
    "scenario": "normal_shipping_order_01",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "dispatch@sableridgematerials.com",
    "subject": "Pickup request - stainless sheet to Fab 11",
    "text": "From: dispatch@sableridgematerials.com\nSubject: Pickup request - stainless sheet to Fab 11\n\nHi logistics team,\n\n        Please arrange a truckload pickup of the 304 stainless sheet order for\n        Fab 11. We have 25 sheets (4x8ft, 16ga) ready, total weight\n        approximately 9,800 lbs. We can have it ready for pickup on\n        2026-08-24.\n\n        Shipper: Sable Ridge Materials, 4100 Foundry Rd, Twin Falls, ID\n        Consignee: Fab 11 - Boise, ID\n\n        Thanks,\n        Sable Ridge Materials Dispatch"
  },
  {
    "id": "002_shipping_normal",
    "scenario": "normal_shipping_order_02",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "shipping@ironharborfab.com",
    "subject": "LTL delivery - welded frame assemblies for Manassas",
    "text": "From: shipping@ironharborfab.com\nSubject: LTL delivery - welded frame assemblies for Manassas\n\nGood morning,\n\n        We'd like to schedule an LTL delivery of the welded steel frame\n        assemblies (15 units, Rev C) to the Manassas site. Estimated weight\n        is 2,100 lbs. Requested pickup date is 2026-08-26 from our Duluth,\n        MN facility.\n\n        Shipper: Iron Harbor Fabrication\n        Consignee: Manassas Site - Manassas, VA\n\n        Best,\n        Iron Harbor Fabrication Shipping"
  },
  {
    "id": "003_shipping_normal",
    "scenario": "normal_shipping_order_03",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "logistics@vantagepointelec.com",
    "subject": "Air freight needed - component kits to Singapore",
    "text": "From: logistics@vantagepointelec.com\nSubject: Air freight needed - component kits to Singapore\n\nHello,\n\n        We need to air-ship the SMD component kits (resistor + capacitor\n        assortments, 400 units combined, ~140 lbs) to the Singapore Fab as\n        soon as possible - production is waiting on these. Pickup can happen\n        tomorrow, 2026-08-21, from our San Jose warehouse.\n\n        Shipper: Vantage Point Electronics\n        Consignee: Singapore Fab - Woodlands\n\n        Regards,\n        Vantage Point Electronics Logistics"
  },
  {
    "id": "004_shipping_normal",
    "scenario": "normal_shipping_order_04",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "ops@anchorpointpkg.com",
    "subject": "Truckload - foam inserts to Lehi DC",
    "text": "From: ops@anchorpointpkg.com\nSubject: Truckload - foam inserts to Lehi DC\n\nHi team,\n\n        Ready to ship the ESD-safe foam insert order (3,000 units, roughly\n        6,200 lbs) via full truckload to the Lehi distribution center.\n        Pickup available 2026-08-25 from our Reno plant.\n\n        Shipper: Anchor Point Packaging\n        Consignee: Distribution Center - Lehi, UT\n\n        Thanks,\n        Anchor Point Packaging Ops"
  },
  {
    "id": "005_shipping_normal",
    "scenario": "normal_shipping_order_05",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "shipping@northfieldcomponents.com",
    "subject": "LTL pickup - aluminum brackets to Boise",
    "text": "From: shipping@northfieldcomponents.com\nSubject: LTL pickup - aluminum brackets to Boise\n\nHello,\n\n        Please schedule an LTL pickup for the aluminum bracket shipment (480\n        units, Type-C, approx. 1,050 lbs) heading to Fab 11 in Boise. We can\n        have the pallets ready 2026-08-23.\n\n        Shipper: Northfield Components\n        Consignee: Fab 11 - Boise, ID\n\n        Thank you,\n        Northfield Components Shipping"
  },
  {
    "id": "006_shipping_normal",
    "scenario": "normal_shipping_order_06",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "dispatch@meridiantooling.com",
    "subject": "Truckload shipment - tooling to Manassas",
    "text": "From: dispatch@meridiantooling.com\nSubject: Truckload shipment - tooling to Manassas\n\nHi,\n\n        Our CNC end mill order is ready. We'd like to book a truckload\n        shipment (60 sets, ~3,400 lbs including packaging) to the Manassas\n        site, pickup on 2026-08-27 from our Cleveland facility.\n\n        Shipper: Meridian Tooling Co\n        Consignee: Manassas Site - Manassas, VA\n\n        Thanks,\n        Meridian Tooling Co Dispatch"
  },
  {
    "id": "007_shipping_normal",
    "scenario": "normal_shipping_order_07",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "facilities.boise@micron.com",
    "subject": "Inter-site transfer - surplus equipment Boise to Lehi",
    "text": "From: facilities.boise@micron.com\nSubject: Inter-site transfer - surplus equipment Boise to Lehi\n\nHi logistics,\n\n        We have surplus test equipment racks to transfer from Fab 11 in\n        Boise to the Lehi distribution center for redeployment. Estimated\n        weight 4,500 lbs, LTL is fine. Target pickup 2026-08-28.\n\n        Shipper: Fab 11 - Boise, ID\n        Consignee: Distribution Center - Lehi, UT\n\n        Thanks,\n        Micron Facilities - Boise"
  },
  {
    "id": "008_shipping_normal",
    "scenario": "normal_shipping_order_08",
    "docTypeExpected": "shipping_order",
    "plantedFlaw": null,
    "from": "export@cascadeprecisionmachining.com",
    "subject": "Ocean freight booking - machined parts to Singapore",
    "text": "From: export@cascadeprecisionmachining.com\nSubject: Ocean freight booking - machined parts to Singapore\n\nHello,\n\n        We need to book ocean freight for a container of precision-machined\n        parts heading to the Singapore Fab. Total weight approximately\n        18,000 lbs. Ready for pickup at our Long Beach staging warehouse on\n        2026-09-02.\n\n        Shipper: Cascade Precision Machining\n        Consignee: Singapore Fab - Woodlands\n\n        Regards,\n        Cascade Precision Machining Export Desk"
  },
  {
    "id": "009_po_normal",
    "scenario": "normal_purchase_order_01",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "procurement.boise@micron.com",
    "subject": "New PO needed - additional aluminum brackets",
    "text": "From: procurement.boise@micron.com\nSubject: New PO needed - additional aluminum brackets\n\nHi procurement,\n\n        We're running low on Type-C aluminum brackets ahead of the next\n        production run. Please place a new order with Northfield Components\n        for 600 units at their standard unit price ($12.40). Requested\n        delivery date is 2026-09-10, ship to Fab 11 - Boise.\n\n        Thanks,\n        Fab 11 Manufacturing Engineering"
  },
  {
    "id": "010_po_normal",
    "scenario": "normal_purchase_order_02",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "eng.manassas@micron.com",
    "subject": "Order more stainless sheet",
    "text": "From: eng.manassas@micron.com\nSubject: Order more stainless sheet\n\nHi team,\n\n        Please issue a new purchase order to Sable Ridge Materials for 40\n        sheets of 304 stainless (4x8ft, 16ga) at $210.00/sheet. We need it by\n        2026-09-15 at the Manassas site.\n\n        Thanks,\n        Manassas Engineering"
  },
  {
    "id": "011_po_normal",
    "scenario": "normal_purchase_order_03",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "procurement.sg@micron.com",
    "subject": "New order - SMD component kits",
    "text": "From: procurement.sg@micron.com\nSubject: New order - SMD component kits\n\nHello,\n\n        Please place an order with Vantage Point Electronics for 300 SMD\n        resistor kits (0603 assorted, $9.75 each) and 300 SMD capacitor kits\n        (0805 assorted, $11.25 each). Requested delivery 2026-09-08, ship to\n        Singapore Fab - Woodlands.\n\n        Thanks,\n        Singapore Fab Procurement"
  },
  {
    "id": "012_po_normal",
    "scenario": "normal_purchase_order_04",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "ops.lehi@micron.com",
    "subject": "Need a new PO for packaging foam",
    "text": "From: ops.lehi@micron.com\nSubject: Need a new PO for packaging foam\n\nHi,\n\n        Please issue a purchase order to Anchor Point Packaging for 5,000\n        units of the custom die-cut ESD-safe foam insert at $1.85/unit.\n        Requested delivery date 2026-09-12, ship to Distribution Center -\n        Lehi, UT.\n\n        Thanks,\n        Lehi DC Operations"
  },
  {
    "id": "013_po_normal",
    "scenario": "normal_purchase_order_05",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "eng.boise@micron.com",
    "subject": "Order welded frame assemblies",
    "text": "From: eng.boise@micron.com\nSubject: Order welded frame assemblies\n\nHi procurement,\n\n        Please place a new order with Iron Harbor Fabrication for 20 welded\n        steel frame assemblies (Rev C) at $640.00/unit. Requested delivery\n        2026-09-20, ship to Fab 11 - Boise, ID.\n\n        Thanks,\n        Fab 11 Engineering"
  },
  {
    "id": "014_po_normal",
    "scenario": "normal_purchase_order_06",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "eng.manassas@micron.com",
    "subject": "New tooling order",
    "text": "From: eng.manassas@micron.com\nSubject: New tooling order\n\nHi team,\n\n        We need another batch of CNC end mills. Please issue a purchase\n        order to Meridian Tooling Co for 45 sets at $84.00/set, requested\n        delivery 2026-09-18, ship to Manassas Site - Manassas, VA.\n\n        Thanks,\n        Manassas Engineering"
  },
  {
    "id": "015_po_normal",
    "scenario": "normal_purchase_order_07",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": null,
    "from": "procurement.boise@micron.com",
    "subject": "Order precision-machined parts",
    "text": "From: procurement.boise@micron.com\nSubject: Order precision-machined parts\n\nHi procurement,\n\n        Please place an order with Cascade Precision Machining for 25 units\n        of the precision-machined bracket assembly at $145.00/unit.\n        Requested delivery date 2026-09-22, ship to Fab 11 - Boise, ID.\n\n        Thanks,\n        Fab 11 Procurement"
  },
  {
    "id": "016_invoice_normal",
    "scenario": "normal_invoice_01",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "ap@northfieldcomponents.com",
    "subject": "Invoice INV-88213 for PO-10045",
    "text": "From: ap@northfieldcomponents.com\nSubject: Invoice INV-88213 for PO-10045\n\nHi team,\n\n        Please find our invoice INV-88213 for PO-10045: 480 units of\n        precision aluminum brackets at $12.40/unit, total $5,952.00, due net\n        30 (2026-09-20).\n\n        Thanks,\n        Northfield Components AP Team"
  },
  {
    "id": "017_invoice_normal",
    "scenario": "normal_invoice_02",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "billing@meridiantooling.com",
    "subject": "Invoice MT-4471 for PO-10062",
    "text": "From: billing@meridiantooling.com\nSubject: Invoice MT-4471 for PO-10062\n\nHello,\n\n        Invoice MT-4471 for PO-10062: 60 CNC end mill sets at $84.00/set,\n        total $5,040.00. Payment terms net 30, due 2026-09-18.\n\n        Regards,\n        Meridian Tooling Co Billing"
  },
  {
    "id": "018_invoice_normal",
    "scenario": "normal_invoice_03",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "ap@sableridgematerials.com",
    "subject": "Invoice SR-9012 - PO-10071",
    "text": "From: ap@sableridgematerials.com\nSubject: Invoice SR-9012 - PO-10071\n\nHi,\n\n        Attached invoice SR-9012 against PO-10071: 25 sheets of 304\n        stainless (4x8ft, 16ga) at $210.00/sheet, total $5,250.00, due net 30\n        (2026-09-22).\n\n        Thanks,\n        Sable Ridge Materials AP"
  },
  {
    "id": "019_invoice_normal",
    "scenario": "normal_invoice_04",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "billing@vantagepointelec.com",
    "subject": "Invoice VP-33210 for PO-10088",
    "text": "From: billing@vantagepointelec.com\nSubject: Invoice VP-33210 for PO-10088\n\nHello,\n\n        Invoice VP-33210 against PO-10088:\n        - SMD resistor kit, 0603 assorted: 200 units @ $9.75 = $1,950.00\n        - SMD capacitor kit, 0805 assorted: 200 units @ $11.25 = $2,250.00\n\n        Total: $4,200.00. Due net 30 (2026-09-25).\n\n        Thanks,\n        Vantage Point Electronics Billing"
  },
  {
    "id": "020_invoice_normal",
    "scenario": "normal_invoice_05",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "ap@ironharborfab.com",
    "subject": "Invoice IH-5567 - PO-10093",
    "text": "From: ap@ironharborfab.com\nSubject: Invoice IH-5567 - PO-10093\n\nHi,\n\n        Invoice IH-5567 against PO-10093: 15 welded steel frame assemblies\n        (Rev C) at $640.00/unit, total $9,600.00, due net 30 (2026-09-24).\n\n        Thanks,\n        Iron Harbor Fabrication AP"
  },
  {
    "id": "021_invoice_normal",
    "scenario": "normal_invoice_06",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "billing@anchorpointpkg.com",
    "subject": "Invoice AP-7788 for PO-10101",
    "text": "From: billing@anchorpointpkg.com\nSubject: Invoice AP-7788 for PO-10101\n\nHello,\n\n        Invoice AP-7788 against PO-10101: 3,000 units of ESD-safe foam\n        insert, custom die-cut, at $1.85/unit, total $5,550.00, due net 30\n        (2026-09-26).\n\n        Thanks,\n        Anchor Point Packaging Billing"
  },
  {
    "id": "022_invoice_normal",
    "scenario": "normal_invoice_07",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "billing@wrenfieldlogistics.com",
    "subject": "Invoice WF-2201 for PO-10112",
    "text": "From: billing@wrenfieldlogistics.com\nSubject: Invoice WF-2201 for PO-10112\n\nHi,\n\n        Invoice WF-2201 against PO-10112: dedicated truckload freight\n        service, Boise-Lehi lane, 1 unit at $2,400.00, total $2,400.00, due\n        net 15 (2026-09-05).\n\n        Thanks,\n        Wrenfield Logistics Partners Billing"
  },
  {
    "id": "023_invoice_normal",
    "scenario": "normal_invoice_08",
    "docTypeExpected": "invoice",
    "plantedFlaw": null,
    "from": "ap@cascadeprecisionmanufacturing.com",
    "subject": "Invoice CPM-6640 - PO-10125",
    "text": "From: ap@cascadeprecisionmanufacturing.com\nSubject: Invoice CPM-6640 - PO-10125\n\nHello,\n\n        Invoice CPM-6640 against PO-10125: 40 units of precision-machined\n        housing, Rev B, at $96.50/unit, total $3,860.00, due net 30\n        (2026-09-28).\n\n        Thanks,\n        Cascade Precision Manufacturing AP"
  },
  {
    "id": "024_remit_normal",
    "scenario": "normal_remittance_01",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - payment to Northfield Components",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - payment to Northfield Components\n\nHi,\n\n        This confirms payment of $5,952.00 to Northfield Components,\n        settling invoice INV-88213. Payment reference: ACH-771029.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "025_remit_normal",
    "scenario": "normal_remittance_02",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - two invoices settled, Sable Ridge Materials",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - two invoices settled, Sable Ridge Materials\n\nHi,\n\n        Payment reference WIRE-550213 settles two invoices for Sable Ridge\n        Materials: SR-9012 for $5,250.00 and SR-9013 for $1,800.00.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "026_remit_normal",
    "scenario": "normal_remittance_03",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - Iron Harbor Fabrication",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - Iron Harbor Fabrication\n\nHi,\n\n        Payment reference ACH-771144 settles invoice IH-5567 for $9,600.00\n        to Iron Harbor Fabrication.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "027_remit_normal",
    "scenario": "normal_remittance_04",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - Vantage Point Electronics, two invoices",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - Vantage Point Electronics, two invoices\n\nHi,\n\n        Payment reference WIRE-550298 settles two Vantage Point Electronics\n        invoices: VP-33210 for $4,200.00 and VP-33255 for $2,975.00.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "028_remit_normal",
    "scenario": "normal_remittance_05",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - Meridian Tooling Co",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - Meridian Tooling Co\n\nHi,\n\n        Payment reference ACH-771190 settles invoice MT-4471 for $5,040.00\n        to Meridian Tooling Co.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "029_remit_normal",
    "scenario": "normal_remittance_06",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - Anchor Point Packaging",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - Anchor Point Packaging\n\nHi,\n\n        Payment reference ACH-771205 settles invoice AP-7788 for $5,550.00\n        to Anchor Point Packaging.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "030_remit_normal",
    "scenario": "normal_remittance_07",
    "docTypeExpected": "remittance_advice",
    "plantedFlaw": null,
    "from": "treasury@micron.com",
    "subject": "Remittance advice - Delacroix Freight & Logistics",
    "text": "From: treasury@micron.com\nSubject: Remittance advice - Delacroix Freight & Logistics\n\nHi,\n\n        Payment reference WIRE-550341 settles invoice DFL-1091 for $3,120.00\n        to Delacroix Freight & Logistics.\n\n        Thanks,\n        Micron Treasury"
  },
  {
    "id": "031_flaw_hallucinated_po",
    "scenario": "hallucinated_po_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "hallucinated_po",
    "from": "ap@northfieldcomponents.com",
    "subject": "Invoice for units from your recent shipment",
    "text": "From: ap@northfieldcomponents.com\nSubject: Invoice for units from your recent shipment\n\nHi team,\n\n        Please find our invoice for the 500 aluminum brackets from your\n        recent order, at $12.40/unit, total $6,200.00, due net 30\n        (2026-09-27). Invoice number NC-9910.\n\n        Thanks,\n        Northfield Components AP Team"
  },
  {
    "id": "032_flaw_hallucinated_po",
    "scenario": "hallucinated_po_2",
    "docTypeExpected": "invoice",
    "plantedFlaw": "hallucinated_po",
    "from": "billing@meridiantooling.com",
    "subject": "Invoice for the tooling we discussed",
    "text": "From: billing@meridiantooling.com\nSubject: Invoice for the tooling we discussed\n\nHello,\n\n        Attached is invoice MT-4502 for the 75 CNC end mill sets from the\n        order we discussed last month, at $84.00/set, total $6,300.00. Due\n        net 30 (2026-09-29).\n\n        Regards,\n        Meridian Tooling Co Billing"
  },
  {
    "id": "033_flaw_currency_mismatch",
    "scenario": "currency_mismatch_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "currency_mismatch",
    "from": "ap@balticcircuitworks.com",
    "subject": "Invoice BCW-2201 for PO-10140",
    "text": "From: ap@balticcircuitworks.com\nSubject: Invoice BCW-2201 for PO-10140\n\nHi,\n\n        Invoice BCW-2201 against PO-10140: 500 units of 6-layer custom PCB\n        at $18.20/unit, total $9,100.00 USD. Due net 30 (2026-09-30).\n\n        Thanks,\n        Baltic Circuit Works AP"
  },
  {
    "id": "034_flaw_currency_mismatch",
    "scenario": "currency_mismatch_2",
    "docTypeExpected": "invoice",
    "plantedFlaw": "currency_mismatch",
    "from": "ap@balticcircuitworks.com",
    "subject": "Invoice BCW-2214 for PO-10140",
    "text": "From: ap@balticcircuitworks.com\nSubject: Invoice BCW-2214 for PO-10140\n\nHello,\n\n        Invoice BCW-2214 against PO-10140: 500 units of 6-layer custom PCB\n        at \u00a314.60/unit, total \u00a37,300.00. Due net 30 (2026-10-02).\n\n        Thanks,\n        Baltic Circuit Works AP"
  },
  {
    "id": "035_flaw_escalation_drop",
    "scenario": "escalation_drop_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "escalation_silent_failure",
    "from": "ap@delacroixfreight.com",
    "subject": "Invoice DFL-1102 for PO-99981",
    "text": "From: ap@delacroixfreight.com\nSubject: Invoice DFL-1102 for PO-99981\n\nHi,\n\n        Invoice DFL-1102 against PO-99981: linehaul freight service, 1 unit\n        at $3,450.00, total $3,450.00. Due net 15 (2026-09-05).\n\n        Thanks,\n        Delacroix Freight & Logistics AP"
  },
  {
    "id": "036_flaw_escalation_drop",
    "scenario": "escalation_drop_2",
    "docTypeExpected": "invoice",
    "plantedFlaw": "escalation_silent_failure",
    "from": "billing@omalleyindustrial.com",
    "subject": "Invoice OM-6602 referencing PO-10062",
    "text": "From: billing@omalleyindustrial.com\nSubject: Invoice OM-6602 referencing PO-10062\n\nHello,\n\n        Invoice OM-6602 against PO-10062: 30 units of industrial fastener\n        assortment at $22.00/unit, total $660.00. Due net 30 (2026-09-19).\n\n        Thanks,\n        O'Malley Industrial Supply Billing"
  },
  {
    "id": "037_flaw_wrong_tool",
    "scenario": "wrong_tool_classification_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "wrong_tool_classification",
    "from": "ap@sableridgematerials.com",
    "subject": "Invoice for your recent order PO-10071",
    "text": "From: ap@sableridgematerials.com\nSubject: Invoice for your recent order PO-10071\n\nHi team,\n\n        Invoice SR-9044 for PO-10071: 25 sheets of 304 stainless (4x8ft,\n        16ga) at $210.00/sheet, total $5,250.00, due net 30 (2026-09-23).\n        This is an invoice, not a new order request - please process for\n        payment.\n\n        Thanks,\n        Sable Ridge Materials AP"
  },
  {
    "id": "038_flaw_wrong_tool",
    "scenario": "wrong_tool_classification_2",
    "docTypeExpected": "invoice",
    "plantedFlaw": "wrong_tool_classification",
    "from": "billing@vantagepointelec.com",
    "subject": "Order INV-77401 - Payment Due",
    "text": "From: billing@vantagepointelec.com\nSubject: Order INV-77401 - Payment Due\n\nHello,\n\n        Please process invoice INV-77401 against PO-10088 for payment: SMD\n        component kits as previously supplied, total $4,200.00, due net 30\n        (2026-09-24). This invoice covers goods already delivered.\n\n        Thanks,\n        Vantage Point Electronics Billing"
  },
  {
    "id": "039_flaw_credit_memo",
    "scenario": "missing_credit_memo_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "missing_credit_memo_capability",
    "from": "ap@ironharborfab.com",
    "subject": "Invoice IH-5602 with partial credit for damaged units",
    "text": "From: ap@ironharborfab.com\nSubject: Invoice IH-5602 with partial credit for damaged units\n\nHi,\n\n        Invoice IH-5602 against PO-10093: 15 welded steel frame assemblies\n        at $640.00/unit, subtotal $9,600.00. Two units arrived damaged in\n        transit, so we're applying a credit of -$1,280.00 for those units.\n        Net amount due: $8,320.00, net 30 (2026-09-24).\n\n        Thanks,\n        Iron Harbor Fabrication AP"
  },
  {
    "id": "040_flaw_credit_memo",
    "scenario": "missing_credit_memo_2",
    "docTypeExpected": "invoice",
    "plantedFlaw": "missing_credit_memo_capability",
    "from": "billing@anchorpointpkg.com",
    "subject": "Invoice AP-7801 - includes return credit from prior shipment",
    "text": "From: billing@anchorpointpkg.com\nSubject: Invoice AP-7801 - includes return credit from prior shipment\n\nHello,\n\n        Invoice AP-7801 against PO-10101: 3,000 units foam insert at\n        $1.85/unit, subtotal $5,550.00. We're also crediting $310.00 for the\n        over-shipped units returned from our last delivery. Net total due:\n        $5,240.00, due net 30 (2026-09-26).\n\n        Thanks,\n        Anchor Point Packaging Billing"
  },
  {
    "id": "041_flaw_looping",
    "scenario": "agent_looping_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "agent_looping",
    "from": "ap@cascadeprecision.com",
    "subject": "Invoice CP-4402 - Cascade Precision",
    "text": "From: ap@cascadeprecision.com\nSubject: Invoice CP-4402 - Cascade Precision\n\nHi,\n\n        Invoice CP-4402 for 40 units of precision-machined housing at\n        $96.50/unit, total $3,860.00, due net 30 (2026-09-28).\n\n        Thanks,\n        Cascade Precision AP"
  },
  {
    "id": "042_flaw_looping",
    "scenario": "agent_looping_2",
    "docTypeExpected": "purchase_order",
    "plantedFlaw": "agent_looping",
    "from": "eng.boise@micron.com",
    "subject": "Order more from Cascade Precision again",
    "text": "From: eng.boise@micron.com\nSubject: Order more from Cascade Precision again\n\nHi procurement,\n\n        Please order another 25 units of the precision-machined bracket\n        assembly, same as before, from Cascade Precision. Requested delivery\n        2026-09-22, ship to Fab 11 - Boise, ID.\n\n        Thanks,\n        Fab 11 Procurement"
  },
  {
    "id": "043_flaw_prompt_drift",
    "scenario": "prompt_drift_padded_total_1",
    "docTypeExpected": "invoice",
    "plantedFlaw": "system_prompt_drift",
    "from": "ap@sableridgematerials.com",
    "subject": "Invoice SR-9077 for PO-10071",
    "text": "From: ap@sableridgematerials.com\nSubject: Invoice SR-9077 for PO-10071\n\nHi,\n\n        Invoice SR-9077 against PO-10071: 25 sheets of 304 stainless (4x8ft,\n        16ga) at $210.00/sheet. Total due: $5,700.00, net 30 (2026-09-23).\n\n        Thanks,\n        Sable Ridge Materials AP"
  },
  {
    "id": "044_flaw_prompt_drift",
    "scenario": "prompt_drift_padded_total_2",
    "docTypeExpected": "invoice",
    "plantedFlaw": "system_prompt_drift",
    "from": "ap@northfieldcomponents.com",
    "subject": "Invoice NC-9944 for PO-10045",
    "text": "From: ap@northfieldcomponents.com\nSubject: Invoice NC-9944 for PO-10045\n\nHi team,\n\n        Invoice NC-9944 for PO-10045: 480 units of precision aluminum\n        brackets at $12.40/unit. Total due: $6,800.00, due net 30\n        (2026-09-20).\n\n        Thanks,\n        Northfield Components AP Team"
  },
  {
    "id": "045_oos_customs",
    "scenario": "out_of_scope_customs_inquiry",
    "docTypeExpected": "out_of_scope",
    "plantedFlaw": null,
    "from": "broker@globalcustomsadvisors.com",
    "subject": "HTS classification question for upcoming import",
    "text": "From: broker@globalcustomsadvisors.com\nSubject: HTS classification question for upcoming import\n\nHi,\n\n        We're preparing the customs paperwork for an upcoming import and\n        need to confirm the correct HTS classification code for the\n        precision-machined aluminum components before they ship. Can someone\n        from your compliance team advise on the correct code and applicable\n        duty rate?\n\n        Thanks,\n        Global Customs Advisors"
  },
  {
    "id": "046_oos_non_english",
    "scenario": "out_of_scope_non_english",
    "docTypeExpected": "out_of_scope",
    "plantedFlaw": null,
    "from": "facturacion@proveedorlatam.com",
    "subject": "Factura FP-2291 por orden de compra",
    "text": "From: facturacion@proveedorlatam.com\nSubject: Factura FP-2291 por orden de compra\n\nEstimados,\n\n        Adjunto la factura FP-2291 correspondiente a la orden de compra\n        reciente: 200 unidades de conectores industriales a $8.40/unidad,\n        total $1,680.00. Vencimiento a 30 dias.\n\n        Saludos,\n        Proveedor LatAm - Facturacion"
  },
  {
    "id": "047_oos_garbled",
    "scenario": "out_of_scope_garbled_ocr",
    "docTypeExpected": "out_of_scope",
    "plantedFlaw": null,
    "from": "scans@sharedmailbox.internal",
    "subject": "Fwd: Scanned document 08-19",
    "text": "From: scans@sharedmailbox.internal\nSubject: Fwd: Scanned document 08-19\n\nFWD from scanner -\n\n        I\u2013nvo1c3 N0. ####7 P0#: 10-0-45 Qty: 4B0 U/P: 1?.40\n        T0tal: $$,,952.00 rn3t 3o d4ys  ***PAGE 1 OF 1 - LOW QUALITY SCAN***\n        [illegible] [illegible] pls advise\n\n        - front desk"
  },
  {
    "id": "048_oos_relationship",
    "scenario": "out_of_scope_vendor_notice",
    "docTypeExpected": "out_of_scope",
    "plantedFlaw": null,
    "from": "notices@ironharborfab.com",
    "subject": "Planned facility closure - Labor Day",
    "text": "From: notices@ironharborfab.com\nSubject: Planned facility closure - Labor Day\n\nHi,\n\n        Just a heads up that our Duluth facility will be closed for Labor\n        Day (2026-09-07) and shipping will resume 2026-09-08. No action\n        needed on your end - just wanted to flag this in case you're\n        planning any pickups around that date.\n\n        Thanks,\n        Iron Harbor Fabrication"
  },
  {
    "id": "049_oos_marketing",
    "scenario": "out_of_scope_marketing",
    "docTypeExpected": "out_of_scope",
    "plantedFlaw": null,
    "from": "sales@vantagepointelec.com",
    "subject": "New 2027 component catalog now available",
    "text": "From: sales@vantagepointelec.com\nSubject: New 2027 component catalog now available\n\nHi,\n\n        Our new 2027 catalog is live with expanded SMD component options and\n        volume pricing tiers. Let us know if you'd like a walkthrough with\n        your account rep - we're happy to set up time.\n\n        Best,\n        Vantage Point Electronics Sales"
  },
  {
    "id": "050_oos_internal",
    "scenario": "out_of_scope_internal_hr",
    "docTypeExpected": "out_of_scope",
    "plantedFlaw": null,
    "from": "hr@micron.com",
    "subject": "Open enrollment reminder - action needed by 8/31",
    "text": "From: hr@micron.com\nSubject: Open enrollment reminder - action needed by 8/31\n\nHi all,\n\n        This is a reminder that open enrollment for benefits closes 8/31.\n        Please log into the benefits portal to make your elections if you\n        haven't already.\n\n        Thanks,\n        Micron HR"
  }
];
