"""Export fixtures/emails/*.json into a TypeScript module the frontend's
inbox sidebar imports directly (no runtime fetch needed).

fixtures/emails/*.json is the single source of truth - re-run this after
editing generate_synthetic_emails.py and regenerating fixtures.

    uv run python scripts/export_frontend_emails.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURES_DIR = ROOT / "fixtures" / "emails"
OUT_PATH = ROOT / "frontend" / "src" / "data" / "sampleEmails.generated.ts"


def format_email(email: dict) -> str:
    return f"From: {email['from']}\nSubject: {email['subject']}\n\n{email['body']}"


def main() -> None:
    files = sorted(p for p in FIXTURES_DIR.glob("*.json") if p.name != "index.json")
    records = [json.loads(p.read_text(encoding="utf-8")) for p in files]

    entries = []
    for r in records:
        entries.append(
            {
                "id": r["id"],
                "scenario": r["scenario"],
                "docTypeExpected": r["doc_type_expected"],
                "plantedFlaw": r["planted_flaw"],
                "from": r["email"]["from"],
                "subject": r["email"]["subject"],
                "text": format_email(r["email"]),
            }
        )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "// Generated by scripts/export_frontend_emails.py - do not edit by hand.\n"
        "// Source of truth: fixtures/emails/*.json\n\n"
        "export type SampleEmail = {\n"
        "  id: string;\n"
        "  scenario: string;\n"
        "  docTypeExpected: string;\n"
        "  plantedFlaw: string | null;\n"
        "  from: string;\n"
        "  subject: string;\n"
        "  text: string;\n"
        "};\n\n"
        f"export const SAMPLE_EMAILS: SampleEmail[] = {json.dumps(entries, indent=2)};\n"
    )
    OUT_PATH.write_text(body, encoding="utf-8")
    print(f"Wrote {len(entries)} sample emails to {OUT_PATH}")


if __name__ == "__main__":
    main()
